package ru.kos.neb_viewer;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JColorChooser;
import javax.swing.JComponent;
import javax.swing.JFrame;

public class TelnetClient extends javax.swing.JFrame
{
    private JFrame frame;
    AEmulator emu;
    JTerminal term;
    Telnet telnet;
    String server = null;
    int port = 23;

    /** Creates new form TelnetClient */
    public TelnetClient()
    {
        initComponents();
    }

    public void RunTelnet(String ip)
    {
        ip=ip.split(" - ")[0];
        emu = new VTEmulator(new VTMapper(), new VTTranslator());
        term = new JTerminal();
        term.setEmulator(emu);
        telnet = new Telnet(emu);

        frame = new JFrame(ip);

        frame.setContentPane(term);
        Container c = frame.getContentPane();
        c.add(jMenuBar1, BorderLayout.NORTH);

        frame.setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/idle.gif")));
        frame.addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                frame.dispose();
            }
        });
        frame.pack();
        frame.setVisible(true);

        String str = Utils.ReadFile(Main.neb_cfg);
        String s = Utils.GetKeyFromNebCFG(str, "term_font_size");
        if(s != null)
        {
            term.font.size = Integer.valueOf(s);
            term.font.install();
            Dimension ss = frame.getPreferredSize();
            frame.setSize((int)(ss.getWidth()),(int)(ss.getHeight()));
        }
        s = Utils.GetKeyFromNebCFG(str, "term_foreground");
        if(s != null)
        {
            term.setForeground(Short.valueOf(s));
        }
        s = Utils.GetKeyFromNebCFG(str, "term_background");
        if(s != null)
        {
            String[] colors = s.split(",");
            Color col = new Color((Integer.valueOf(colors[0]) << 16) | (Integer.valueOf(colors[1]) << 8) | Integer.valueOf(colors[2]));
            term.view.setBackground(col);
        }
        s = Utils.GetKeyFromNebCFG(str, "term_font_style");
        if(s != null && s.equalsIgnoreCase("plain")) 
        {
            term.setStyle((short)0);
            jCheckBoxMenuItem1.setSelected(true);
            jCheckBoxMenuItem2.setSelected(false);
            jCheckBoxMenuItem3.setSelected(false);
            jCheckBoxMenuItem4.setSelected(false);
        }
        else if(s != null && s.equalsIgnoreCase("bold"))
        {
            term.setStyle((short)1);
            jCheckBoxMenuItem1.setSelected(false);
            jCheckBoxMenuItem2.setSelected(true);
            jCheckBoxMenuItem3.setSelected(false);
            jCheckBoxMenuItem4.setSelected(false);
        }
        else if(s != null && s.equalsIgnoreCase("italic"))
        {
            term.setStyle((short)2);
            jCheckBoxMenuItem1.setSelected(false);
            jCheckBoxMenuItem2.setSelected(false);
            jCheckBoxMenuItem3.setSelected(true);
            jCheckBoxMenuItem4.setSelected(false);
        }
        else if(s != null && s.equalsIgnoreCase("italic_bold"))
        {
            term.setStyle((short)3);
            jCheckBoxMenuItem1.setSelected(false);
            jCheckBoxMenuItem2.setSelected(false);
            jCheckBoxMenuItem3.setSelected(false);
            jCheckBoxMenuItem4.setSelected(true);
        }

        server=ip;
        telnet.connect(server, port);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Terminal");

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pallete.png"))); // NOI18N
        jMenu4.setText("Set Color...");

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spallete.png"))); // NOI18N
        jMenu5.setText("Foreground");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black.png"))); // NOI18N
        jMenuItem4.setText("Black");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark_blue.png"))); // NOI18N
        jMenuItem5.setText("Dark Blue");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark_green.png"))); // NOI18N
        jMenuItem8.setText("Dark Green");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark_turquoise.png"))); // NOI18N
        jMenuItem9.setText("Dark Turquoise");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark_red.png"))); // NOI18N
        jMenuItem10.setText("Dark Red");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark_violet.png"))); // NOI18N
        jMenuItem11.setText("Dark Violet");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark_yellow.png"))); // NOI18N
        jMenuItem12.setText("Dark Yellow");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gray.png"))); // NOI18N
        jMenuItem13.setText("Gray");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark_gray.png"))); // NOI18N
        jMenuItem14.setText("Dark Gray");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue.png"))); // NOI18N
        jMenuItem15.setText("Blue");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green.png"))); // NOI18N
        jMenuItem16.setText("Green");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem16);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/turquoise.png"))); // NOI18N
        jMenuItem17.setText("Turquoise");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red.png"))); // NOI18N
        jMenuItem18.setText("Red");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem18);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/violet.png"))); // NOI18N
        jMenuItem19.setText("Violet");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem19);

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yellow.png"))); // NOI18N
        jMenuItem20.setText("Yellow");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem20);

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/white.png"))); // NOI18N
        jMenuItem21.setText("White");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem21);

        jMenu4.add(jMenu5);

        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spallete.png"))); // NOI18N
        jMenuItem22.setText("Background");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem22);

        jMenu3.add(jMenu4);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sfont.png"))); // NOI18N
        jMenuItem6.setText("Smaller Font");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lfont.png"))); // NOI18N
        jMenuItem7.setText("Larger Font");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/font_style.png"))); // NOI18N
        jMenu6.setText("Font Style");

        jCheckBoxMenuItem1.setText("Plain Text");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setText("Bold Text");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setText("Italic");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem4.setText("Italic Bold");
        jCheckBoxMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jCheckBoxMenuItem4);

        jMenu3.add(jMenu6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem7ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem7ActionPerformed
        term.font.size = term.font.size+2;
        term.font.install();
        Dimension ss = frame.getPreferredSize();
        frame.setSize((int)(ss.getWidth()),(int)(ss.getHeight()));
        String str = Utils.ReadFile(Main.neb_cfg);
        String str1 = Utils.SetKeyToNebCFG(str, "term_font_size", String.valueOf(term.font.size));
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem6ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem6ActionPerformed
        term.font.size = term.font.size-2;
        term.font.install();
        Dimension ss = frame.getPreferredSize();
        frame.setSize((int)(ss.getWidth()),(int)(ss.getHeight()));
        String str = Utils.ReadFile(Main.neb_cfg);
        String str1 = Utils.SetKeyToNebCFG(str, "term_font_size", String.valueOf(term.font.size));
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem4ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem4ActionPerformed
        term.setForeground((short)0);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[0];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "0");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem5ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem5ActionPerformed
        term.setForeground((short)1);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[1];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "1");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem8ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem8ActionPerformed
        term.setForeground((short)2);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[2];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "2");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem9ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem9ActionPerformed
        term.setForeground((short)3);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[3];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "3");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem10ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem10ActionPerformed
        term.setForeground((short)4);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[4];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "4");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem11ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem11ActionPerformed
        term.setForeground((short)5);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[5];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "5");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem12ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem12ActionPerformed
        term.setForeground((short)6);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[6];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "6");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem13ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem13ActionPerformed
        term.setForeground((short)7);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[7];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "7");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem14ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem14ActionPerformed
        term.setForeground((short)8);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[8];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "8");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem15ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem15ActionPerformed
        term.setForeground((short)9);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[9];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "9");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem16ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem16ActionPerformed
        term.setForeground((short)10);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[10];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "10");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem17ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem17ActionPerformed
        term.setForeground((short)11);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[11];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "11");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem18ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem18ActionPerformed
        term.setForeground((short)12);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[12];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "12");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem19ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem19ActionPerformed
        term.setForeground((short)13);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[13];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "13");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem20ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem20ActionPerformed
        term.setForeground((short)14);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[14];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "14");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem21ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem21ActionPerformed
        term.setForeground((short)15);
        String str = Utils.ReadFile(Main.neb_cfg);
        Color c =  term.COLORS[15];
        String str1 = Utils.SetKeyToNebCFG(str, "term_foreground", "15");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem22ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem22ActionPerformed
        Color c = JColorChooser.showDialog(null, "Set background color.", getBackground());
        if (c != null)
        {
            term.view.setBackground(c);
            String str = Utils.ReadFile(Main.neb_cfg);
            String str1 = Utils.SetKeyToNebCFG(str, "term_background", c.getRed()+","+c.getGreen()+","+c.getBlue());
            Utils.WriteFile(Main.neb_cfg, str1, false);
        }
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jCheckBoxMenuItem1ActionPerformed
        term.setStyle((short)0);
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem2.setSelected(false);
        jCheckBoxMenuItem3.setSelected(false);
        jCheckBoxMenuItem4.setSelected(false);
        String str = Utils.ReadFile(Main.neb_cfg);
        String str1 = Utils.SetKeyToNebCFG(str, "term_font_style", "plain");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
    {//GEN-HEADEREND:event_jCheckBoxMenuItem2ActionPerformed
        term.setStyle((short)1);
        jCheckBoxMenuItem1.setSelected(false);
        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem3.setSelected(false);
        jCheckBoxMenuItem4.setSelected(false);
        String str = Utils.ReadFile(Main.neb_cfg);
        String str1 = Utils.SetKeyToNebCFG(str, "term_font_style", "bold");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
    {//GEN-HEADEREND:event_jCheckBoxMenuItem3ActionPerformed
        term.setStyle((short)2);
        jCheckBoxMenuItem1.setSelected(false);
        jCheckBoxMenuItem2.setSelected(false);
        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem4.setSelected(false);
        String str = Utils.ReadFile(Main.neb_cfg);
        String str1 = Utils.SetKeyToNebCFG(str, "term_font_style", "italic");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

    private void jCheckBoxMenuItem4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBoxMenuItem4ActionPerformed
    {//GEN-HEADEREND:event_jCheckBoxMenuItem4ActionPerformed
        term.setStyle((short)3);
        jCheckBoxMenuItem1.setSelected(false);
        jCheckBoxMenuItem2.setSelected(false);
        jCheckBoxMenuItem3.setSelected(false);
        jCheckBoxMenuItem4.setSelected(true);
        String str = Utils.ReadFile(Main.neb_cfg);
        String str1 = Utils.SetKeyToNebCFG(str, "term_font_style", "italic_bold");
        Utils.WriteFile(Main.neb_cfg, str1, false);
    }//GEN-LAST:event_jCheckBoxMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        frame.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new TelnetClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables

}
